version: '2.1'
orbs:
  localstack: localstack/platform@2.1
  
jobs:
  localstack-test:
    executor: localstack/default
    steps:
      - localstack/startup
      - run:
          command: |
            awslocal mq create-broker \
              --broker-name test-broker \
              --deployment-mode SINGLE_INSTANCE \
              --engine-type ACTIVEMQ \
              --engine-version='5.16.6' \
              --host-instance-type 'mq.t2.micro' \
              --auto-minor-version-upgrade \
              --publicly-accessible \
              --users='{"ConsoleAccess": true, "Groups": ["testgroup"],"Password": "QXwV*$iUM9USHnVv&!^7s3c@", "Username": "admin"}'
workflows:
  localstack-test:
    jobs:
      - localstack-test
