pipeline:
  name: Build localstack-in-ci
  identifier: Build_localstack_in_ci_1684161347748
  projectIdentifier: localstackinci
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stage 1
        identifier: Stage_1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: localstack install
                  identifier: localstack_install
                  spec:
                    shell: Sh
                    command: |
                      pip install localstack awscli awscli-local[ver1]
                      docker pull localstack/localstack
                      localstack start -d
                      localstack wait -t 30
              - step:
                  type: Run
                  name: localstack health
                  identifier: localstack_health
                  spec:
                    connectorRef: Docker
                    image: curlimages/curl:7.83.1
                    shell: Sh
                    command: until curl --fail --silent --max-time 1 http://localhost:4566/_localstack/health; do sleep 2; done
              - step:
                  type: Run
                  name: Run AWS CLI tests
                  identifier: run_cli_tests
                  spec:
                    shell: Sh
                    command: |
                      awslocal s3 mb s3://test
                      echo "hello world" > /tmp/hello-world
                      awslocal s3 cp /tmp/hello-world s3://test/hello-world
                      awslocal s3 ls s3://test/
