name: 'Check'
on:
  push:
    branches:
      - main
jobs:
  localstack:
    permissions: write-all
    name: Setup LocalStack Preview
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: '3.4.0'
          install-awslocal: 'true'

      - name: Run Pro CLI features
        run: |
          awslocal s3 mb s3://test
